// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Root endpoint that redirects to the Swagger documentation",
                "tags": [
                    "root"
                ],
                "summary": "Root endpoint",
                "responses": {
                    "301": {
                        "description": "Moved Permanently"
                    }
                }
            }
        },
        "/imgtoad": {
            "post": {
                "description": "Generate marketing suggestions based on an uploaded image file or image URL",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marketing"
                ],
                "summary": "Generate marketing suggestions",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file to analyze",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "URL of the image to analyze",
                        "name": "url",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/aipi_internal_models.MarketingSuggestions"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "aipi_internal_models.MarketingSuggestions": {
            "type": "object",
            "properties": {
                "advertisement": {
                    "type": "string"
                },
                "alt_text": {
                    "type": "string"
                },
                "call_to_action": {
                    "type": "string"
                },
                "content_ideas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cultural_adaptations": {
                    "type": "string"
                },
                "emojis": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "emotional_tone_analysis": {
                    "type": "string"
                },
                "hashtags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "image_enhancement_suggestions": {
                    "type": "string"
                },
                "legal_ethical_considerations": {
                    "type": "string"
                },
                "marketing_strategy_tips": {
                    "type": "string"
                },
                "product_suggestions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "seo_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "social_media_caption": {
                    "type": "string"
                },
                "target_audience_insights": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ADVision API Documentation",
	Description:      "Prototype for API documentation for image processing and marketing suggestions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
