basePath: /
definitions:
  aipi_internal_models.MarketingSuggestions:
    properties:
      advertisement:
        type: string
      alt_text:
        type: string
      call_to_action:
        type: string
      content_ideas:
        items:
          type: string
        type: array
      cultural_adaptations:
        type: string
      emojis:
        items:
          type: string
        type: array
      emotional_tone_analysis:
        type: string
      hashtags:
        items:
          type: string
        type: array
      image_enhancement_suggestions:
        type: string
      legal_ethical_considerations:
        type: string
      marketing_strategy_tips:
        type: string
      product_suggestions:
        items:
          type: string
        type: array
      seo_keywords:
        items:
          type: string
        type: array
      social_media_caption:
        type: string
      target_audience_insights:
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: Prototype for API documentation for image processing and marketing
    suggestions
  title: ADVision API Documentation
  version: "1.0"
paths:
  /:
    get:
      description: Root endpoint that redirects to the Swagger documentation
      responses:
        "301":
          description: Moved Permanently
      summary: Root endpoint
      tags:
      - root
  /imgtoad:
    post:
      consumes:
      - multipart/form-data
      description: Generate marketing suggestions based on an uploaded image file
        or image URL
      parameters:
      - description: Image file to analyze
        in: formData
        name: image
        type: file
      - description: URL of the image to analyze
        in: formData
        name: url
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aipi_internal_models.MarketingSuggestions'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Generate marketing suggestions
      tags:
      - marketing
swagger: "2.0"
